// import { form_json_list } from "../../agentmaker/types/types";

export interface ChatMessage {
  id: string;
  created_user_id: number;
  created_user_name: string;
  created_date: string; // ISO date string, can be converted to Date if needed
  chat_message_type: "text" | "image" | "video" | string; // Extend as needed
  soc_room_id: string;
  attachment_url: string;
  attachment_type: string;
  attachment_name: string;
  sender_id: number;
  receiver_group_id: number | null;
  chat_message: string;
  from_business_number: string;
  from_business_name: string;
}

export interface Latest {
  id: number;
  sender_id: number;
  receiver_id: number;
  sender_user_name: string;
  receiver_user_name: string;
  sender_group_name: string;
  receiver_group_name: string;
  sender_group_code: string;
  receiver_group_code: string;
  chat_message: string;
  ref_chat_message: string;
  created_datetime: string;
  created_user_name: string;
  created_user_id: number;
  business_number: string;
  business_name: string;
  for_business_number: string;
  for_business_name: string;
  ref_business_name: string;
  ref_business_number: string;
}

export interface ChatGroup {
  chat_group_id: number;
  status: string;
  progress_status: string | null;
  chat_group_name: string;
  chat_group_code: string | null;
  chat_group_type: string | null;
  chat_group_category: string | null;
  room_type: string | null;
  room_group: string | null;
  room_name: string | null;
  soc_room_id: string | null;
  room_code: string | null;
  slug: string | null;
  description: string | null;
  short_description: string | null;
  icon: string | null;
  owner_fullname: string | null;
  mobile: string | null;
  email: string | null;
  city: string | null;
  state: string | null;
  country: string | null;
  geolong: number | null;
  geolat: number | null;
  business_number: string;
  business_name: string;
  for_business_number: string;
  for_business_name: string | null;
  ref_business_name: string | null;
  ref_business_number: string | null;
  is_public: boolean | null;
  is_sharable: boolean | null;
  created_user_id: number;
  updated_at_datetime: string | null;
  created_at_datetime: string;
  app_name: string | null;
  created_user_name: string;
  progress_json: JSON;
  status_log_json: JSON;
  user_log_json: JSON;
  business_log_json: JSON;
  agent_json: JSON;
  prompt_json: JSON;
  response_json: JSON;
  timeline_json: JSON;
  chat_group_users_json: ChatGroupUser[];
  chat_room_users_json: JSON;
  chat_team_users_json: JSON;
  chat_community_users_json: JSON;
  custom_text_one: string | null;
  custom_text_two: string | null;
  custom_text_three: string | null;
  custom_json_one: JSON;
  custom_json_two: JSON;
  custom_json_three: JSON;
  custom_no_one: number | null;
  customer_no_two: number | null;
  user_group_list: string;
  agent_uuid: string | null;
  form_uuid: string | null;
  form_setup_id: number | null;
}

export interface ChatGroupUser {
  user_name: string;
  first_name: string | null;
  last_name: string | null;
  avatar_url: string | null;
  profile_pic_url: string | null;
  created_at: string;
  created_user_id: number;
  created_user_name: string;
  user_email: string | null;
  user_mobile: string | null;
  business_number: string;
  business_name: string | null;
  for_business_number: string;
  department: string | null;
  designation: string | null;
  password?: string;
  roles: string | null;
  roles_json: string[] | null;
  user_group_list: string | null;
  business_postcode: string | null;
  business_address_1: string | null;
  business_address_2: string | null;
  business_city: string | null;
  business_state: string | null;
  business_country: string | null;
  business_email: string | null;
  business_description: string | null;
  business_role_title: string | null;
  business_tagline: string | null;
  business_website: string | null;
  business_geo_lat: number | null;
  business_geo_long: number | null;
  business_profile_url: string | null;
  business_logo_url: string | null;
  emailverify: boolean;
  mobileverify: boolean;
  whatsappverify: boolean;
  ref_app_id: string | null;
  ref_appname: string | null;
  ref_user: string | null;
  agent_uuid: string | null;
  form_uuid: string | null;
  app_name: string | null;
  agent_json: JSON;
  flow_json: JSON;
  progress_json: JSON;
  response_json: JSON;
  timeline_json: JSON;
  user_log_json: JSON;
  status_log_json: JSON;
  geo_lat: number | null;
  geo_long: number | null;
  geo_map_url: string | null;
  user_status: string | null;
  profile_url: string | null;
  profile_rating_note: string | null;
  performance_status: string | null;
  billing_address_1: string | null;
  billing_address_2: string | null;
  billing_city: string | null;
  billing_state: string | null;
  billing_country: string | null;
  billing_postcode: string | null;
  billing_email: string | null;
  billing_phone: string | null;
  billing_company: string | null;
  shipping_address_1: string | null;
  shipping_address_2: string | null;
  shipping_city: string | null;
  shipping_state: string | null;
  shipping_country: string | null;
  shipping_postcode: string | null;
  shipping_email: string | null;
  shipping_phone: string | null;
  shipping_first_name: string | null;
  shipping_last_name: string | null;
  company_name: string | null;
  identity_number: string | null;
  document_no: string | null;
  document_status: string | null;
  reset_token: string | null;
  reset_token_expiry: string | null;
  passport_number: string | null;
  registration_number: string | null;
  business_registration_no: string | null;
  business_registration_file: string | null;
  business_registration_type: string | null;
  business_short_description: string | null;
  digital_signature: string | null;
  digital_signature_file: string | null;
  business_intro: string | null;
  business_log_json: JSON;
  contact_user: string | null;
  prompt_json: JSON;
  ref_datetime: string | null;
  ref_business: string | null;
  ref_business_number: string | null;
  for_business_name: string | null;
  for_business_code: string | null;
  start_date: string | null;
  end_date: string | null;
  new_user_join: boolean | null;
  paying_customer: boolean | null;
  loggedin_status: boolean | null;
  preferred_login_mode: string | null;
  signup_social_login: boolean | null;
  social_login_used: boolean | null;
  social_login_provider: string | null;
  social_login_username: string | null;
  classification_code: string | null;
  tourism_tax_number: string | null;
  export_license_no: string | null;
  import_license_no: string | null;
  form_setup_id: number | null;
  user_catalog_id: number;
  flow_routing: string | null;
  html_content: string | null;
  user_note: string | null;
  user_otp: string | null;
  custom_one: string | null;
  custom_two: string | null;
  custom_three: string | null;
  custom_text_area: string | null;
  custom_json_one: JSON;
  custom_json_two: JSON;
  custom_json_three: JSON;
}

//form_setup

export type FormSetupData = FormSetup[];

export interface FormSetup {
  users_json: JSON;
  form_json: form_json_list;
  custom_one: JSON;
  data_connection_json: JSON;
  created_date: string; // or Date
  form_id: string; // bigint
  updated_date: string; // or Date
  content: JSON;
  content_json: JSON;
  share_url_status: boolean;
  for_user_id: string;
  for_user_name: string;
  business_code: string;
  business_name: string;
  business_number: string;
  form_name: string;
  form_code: string;
  form_description: string;
  tabbed_form: string;
  template: string;
  template_name: string;
  chat_form: string;
  chatform_name: string;
  chatform_url: string;
  app_name: string;
  app_code: string;
  page_name: string;
  database_name: string;
  data_table_name: string;
  data_api_name: string;
  data_api_url: string;
  data_api_key: string;
  form_entries_table: string;
  form_entries_table_api: string;
  form_entries_api: string;
  publish_status: string;
  form_publish_date: string;
  form_publish_url: string;
  visits: string;
  submissions: string;
  share_url: string;
  shorturl: string;
  chatformshorturl: string;
  form_iframe_code: string;
  chatform_iframe_code: string;
  no_of_tabs: string;
  tab_name: string;
  tab_number: string;
  tab_order: string;
  tab_field_order: string;
  form_fields_json: string;
  form_fields_script: string;
  version_no: string;
  version_date: string;
  custom_two: string;
  custom_no_one: string;
  custom_no_two: string;
  form_api: string;
  form_success_url: string;
  form_success_message: string;
  form_group: string;
  share_json: string;
  workflow_json: string;
  onboard_json: string;
  custom_one_json: string;
  custom_two_json: string;
  form_icon: string;
  story_name: string;
  story_code: string;
  form_uuid: string;
  agent_uuid: string;
  chat_log_json: string;
  business_log_json: string;
  agent_json: string;
  agent_content_json: string;
  message_content_json: string;
  prompt_json: string;
  response_json: string;
  timeline_json: string;
  email_content_json: string;
  email_doc_json: string;
  db_connection_json: string;
  doc_connection_json: string;
  data_source_json: string;
  connection_logs: string;
  connection_success: string;
  board_agent_code: string;
  board_agent_uuid: string;
  board_agent_id: string;
  ref_agent_id: string;
  ref_agent_uuid: string;
  board_agent_name: string;
  story_api: string;
  api_connection_json: string;
  status: string;
  created_user_id: string;
  created_user_name: string;
  ref_user_id: string;
  ref_user_name: string;
  data_source_name: string;
}

export type form_json_list = form_json[];

export interface form_json {
  name: string;
  type: string;
  label: string;
  value: string;
  checked: boolean;
  variant: string;
  disabled: boolean;
  required: boolean;
  rowIndex: number;
  description: string;
  placeholder: string;
  variant_code: string;
  validation_message: string;
  options?: string[];
  combobox?: string[];
  radiogroup?: string[];
  multiselect?: string[];
  chat_with_data?: ChatWithData;
  media_card_data?: MediaCardData;
  use_settings_upload?: boolean;
  placeholder_file_url?: string;
  placeholder_video_url?: string;
  placeholder_pdf_file_url?: string;
  placeholder_file_upload_url?: string;
}

export interface ChatWithData {
  buttons: Button[];
}

export interface Button {
  prompt: string;
  metricApi: string;
  storyCode: string;
  storyName: string;
  enable_api: boolean;
  button_text: string;
  api_response: string[];
  apiDataFilter: string;
  enable_prompt: boolean;
  component_name: string;
  enable_dataApi: boolean;
  storyApiEnabled: boolean;
  dataApi_response: string[];
  metricApiEnabled: boolean;
  promptDataFilter: string;
}

export interface MediaCardData {
  card_json: string[];
  card_type: string;
  media_url: string;
  use_upload: boolean;
  action_urls: ActionUrls;
  custom_html: string;
  component_name: string;
}

export interface ActionUrls {
  chat: string;
  like: string;
  task: string;
  share: string;
  favorite: string;
}
