export interface StoryGroup {
  data_group_id: number;
  data_group_type: string;
  code: string | null;
  ref_code: string | null;
  for_code: string | null;
  data_group_category: string;
  data_group_name: string;
  name: string;
  ref_name: string | null;
  for_name: string | null;
  short_description: string | null;
  description: string | null;
  remarks: string | null;
  data_model_json: {
    source_table_name: string;
    target_table_name: string;
    extract_metric_group_scope: {
      Numeric: "yes" | "no";
      Date: "yes" | "no";
      Text: "yes" | "no";
    };
    columns: {
      column_name: string;
      column_type: string;
      required: boolean;
      extract_metrics: boolean;
      target_column_name: string;
      extract_metric_group: string;
    }[];
  };
  data_combination_json: string;
  custom_text_one: string | null;
  custom_text_two: string | null;
  custom_number_one: number | null;
  custom_number_two: number | null;
  custom_file_one: string | null;
  custom_file_two: string | null;
  custom_json_one: string | null;
  custom_json_two: string | null;
  business_code: string | null;
  business_name: string;
  business_number: string;
  for_business_code: string | null;
  for_business_name: string;
  for_business_number: string;
  ref_business_code: string | null;
  ref_business_name: string | null;
  ref_business_number: string | null;
  created_user_id: number;
  created_user_name: string;
  created_date: string;
  updated_date: string;
  for_user_id: number | null;
  for_user_name: string | null;
  status: string;
}

export interface ExtractMetricGroupScope {
  Numeric: "yes" | "no";
  Date: "yes" | "no";
  Text: "yes" | "no";
}

export interface StoryData {
  status?: string;
  created_user_id: number;
  created_user_name: string;
  ref_user_id?: number | null;
  ref_user_name?: string | null;
  created_date: string;
  updated_date?: string | null;
  data_source_name?: string | null;
  for_business_code?: string | null;
  for_business_name?: string | null;
  for_business_number?: string | null;
  for_user_id?: number | null;
  for_user_name?: string | null;
  business_code?: string | null;
  business_name?: string | null;
  business_number?: string | null;
  template_name?: string | null;
  template_type?: string | null;
  template_json?: JSON;
  pug_template?: string | null;
  template_prompt?: string | null;
  prompt_response?: JSON;
  story_category?: string | null;
  story_title: string;
  story_code?: string | null;
  story_description?: string | null;
  story_short_description?: string | null;
  story_extract_metrics?: string;
  story_icon_url?: string | null;
  story_icon?: string | null;
  story_json?: JSON;
  get_story_api?: string | null;
  story_api_url?: string | null;
  story_html?: string | null;
  story_component?: string | null;
  story_action_buttons_json?: JSON;
  app_name?: string | null;
  app_code?: string | null;
  page_name?: string | null;
  database_name?: string | null;
  data_table_name?: string | null;
  data_api_name?: string | null;
  data_api_url?: string | null;
  data_api_key?: string | null;
  story_entries_table?: string | null;
  story_entries_table_api?: string | null;
  story_entries_api?: string | null;
  publish_status?: string | null;
  story_publish_date?: string | null;
  story_publish_url?: string | null;
  content?: string | null;
  content_json?: JSON;
  visits?: number | null;
  submissions?: number | null;
  shareurl?: string | null;
  story_iframe_code?: string | null;
  custom_text_one?: string | null;
  custom_text_two?: string | null;
  custom_text_area_one?: string | null;
  custom_tex_area_two?: string | null;
  custom_json_one?: JSON;
  custom_json_two?: JSON;
  custom_api_one?: string | null;
  custom_api_two?: string | null;
  story_id: number;
  template_code?: string | null;
  ref_template_code?: string | null;
  ref_story_code?: string | null;
  story_data_json?: JSON;
  story_workflow_json?: JSON;
  story_card_json?: JSON;
  story_source?: string | null;
  story_automation_json?: JSON;
  story_prompt?: string | null;
  story_script?: string | null;
  story_response?: string | null;
  story_prompt_log_json?: JSON;
  story_uuid?: string | null;
  story_agents_json?: JSON;
  story_connections_json?: JSON;
  story_users_json?: JSON;
  story_components_json?: JSON;
  story_prompts_json?: JSON;
  story_templates_json?: JSON;
  story_content_json?: JSON;
  story_agent_flow_json?: JSON;
  story_charts_json?: JSON;
  story_group: string;
  story_template_group?: string | null;
  user_defined_story_json?: JSON;
  template_story_json?: JSON;
  metrics_story_json?: JSON;
  metrics_userdefined_story_json?: JSON;
  story_template_text?: string | null;
  pug_template_prompt?: string | null;
  pug_template_prompt_response?: string | null;
  extract_metric_prompt?: string | null;
  story_prompt_response?: string | null;
  extract_metric_prompt_response?: string | null;
  user_defined_prompt?: string | null;
  user_defined_response?: string | null;
  related_story_json?: JSON;
  table_column_json?: Record<string, string>;
  userdefined_table_column_json?: JSON;
  userdefined_extract_metric_scope_json?: {
    data_group_id: number;
    data_group_type: string;
    code?: string | null;
    ref_code?: string | null;
    for_code?: string | null;
    data_group_category?: string;
    data_group_name: string;
    name?: string;
    ref_name?: string | null;
    for_name?: string | null;
    short_description?: string | null;
    description?: string | null;
    remarks?: string | null;
    data_model_json: {
      columns: {
        required: boolean;
        column_name: string;
        column_type: string;
        extract_metrics: boolean;
        target_column_name: string;
      }[];
      source_table_name: string;
      target_table_name?: string;
      extract_metric_group_scope?: Record<string, string>;
    };
    data_combination_json?: JSON;
    custom_text_one?: string | null;
    custom_text_two?: string | null;
    custom_number_one?: number | null;
    custom_number_two?: number | null;
    custom_file_one?: string | null;
    custom_file_two?: string | null;
    custom_json_one?: JSON;
    custom_json_two?: JSON;
    business_code?: string | null;
    business_name?: string;
    business_number?: string;
    for_business_code?: string | null;
    for_business_name?: string | null;
    for_business_number?: string | null;
    ref_business_code?: string | null;
    ref_business_name?: string | null;
    ref_business_number?: string | null;
    created_user_id: number;
    created_user_name: string;
    created_date: string;
    updated_date?: string;
    for_user_id?: number | null;
    for_user_name?: string | null;
    status?: string;
  };
  keyword_extract_metric_json?: string[];
  pug_template_json?: string | null;
  story_extract_metric_json?: string[];
}
